// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rckgmcuxdltqpqsbeiom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJja2dtY3V4ZGx0cXBxc2JlaW9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3Mjc1NzMsImV4cCI6MjA2OTMwMzU3M30.y_3g4f-xkPDmnsc5gnLPQ2QpaP64LTA6AOpVhcAOr7A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});