// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivbdcpmglfjxvridbcid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2YmRjcG1nbGZqeHZyaWRiY2lkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MjYyNzUsImV4cCI6MjA2OTMwMjI3NX0.t0518CtzmoBP2exXplbCo9ebIDDhYkhDMQSuTr6ONvQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});